include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_TO_BE_DEPLOYED: 'docker/collserola/transcribe-service'

stages:
  - transcribe
  - deploy

test:
  image: python:3.11.1-slim-bullseye
  before_script:
    - pip install nose2
  stage: transcribe
  script:
    - apt-get update && apt-get install make -y
    - pip install -r transcribe-batch/requirements.txt
    - cd transcribe-batch && nose2

transcribe-models:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  image: docker:latest
  services:
    - docker:dind

  stage: transcribe
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-models
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-batch/docker/Dockerfile-models
    - docker build --cache-from $IMAGE_NAME --tag transcribe-models --tag $IMAGE_NAME . -f $DOCKER_PATH
    - docker push $IMAGE_NAME

transcribe-service:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  image: docker:latest
  services:
    - docker:dind
  stage: transcribe
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-service
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-service/docker/Dockerfile
    - docker build --cache-from $IMAGE_NAME --tag transcribe-service -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

transcribe-batch:
  needs:
    - transcribe-models

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  image: docker:latest
  services:
    - docker:dind
  stage: transcribe
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-batch
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-batch/docker/Dockerfile
    - docker build --cache-from $IMAGE_NAME -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  extends:
    .default-deploy
