include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_TO_BE_DEPLOYED: 'docker/transcribe-service'

stages:
  - transcribe-service
  - transcribe-batch
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

transcribe-service:
  image: docker:latest
  services:
    - docker:dind
  stage: transcribe-service
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-service
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-service/docker/Dockerfile
    - docker build --cache-from $REPO_NAME --tag transcribe-service -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

transcribe-batch:
  image: docker:latest
  services:
    - docker:dind
  stage: transcribe-batch
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-batch
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-batch/docker/Dockerfile
    - docker build --cache-from $REPO_NAME -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME


deploy:
  stage: deploy
  extends:
    .default-deploy
