variables:
  GIT_SUBMODULE_STRATEGY: recursive


image: docker:latest
services:
  - docker:dind

stages:
  - transcribe-service
  - transcribe-batch

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

transcribe-service:
  stage: transcribe-service
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-service
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-service/docker/Dockerfile
    - docker build --tag transcribe-service -f $DOCKER_PATH --tag $IMAGE_NAME --tag $REPO_NAME:$CI_COMMIT_SHA .
    - docker push $REPO_NAME:$CI_COMMIT_SHA    
    - docker push $IMAGE_NAME

transcribe-batch:
  stage: transcribe-batch
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/transcribe-batch
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=transcribe-batch/docker/Dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME --tag $REPO_NAME:$CI_COMMIT_SHA .
    - docker push $REPO_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME

