services:
  transcribe-service:
    image: transcribe-service:latest
    restart: always
    ports:
      - "8700:8700"

    volumes:
      - transcribe-files:/srv/data

    environment:
      LOGLEVEL: 'DEBUG'
      LOGDIR: "/srv/data/logs"

  transcribe-batch_1:
    image: transcribe-batch:latest
    restart: always

    volumes:
      - transcribe-files:/srv/data

    deploy:
       resources:
         reservations:
           devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

    environment:
      LOGLEVEL: 'DEBUG'
      LOGID: '1'
      LOGDIR: "/srv/data/logs"
      DEVICE: 'cuda'
      DEVICE_INDEX: "0"

  transcribe-batch_2:
    image: transcribe-batch:latest
    restart: always

    volumes:
      - transcribe-files:/srv/data

    environment:
      LOGLEVEL: 'DEBUG'
      LOGID: '2'      
      LOGDIR: "/srv/data/logs"

volumes:
  transcribe-files:
