FROM python:3.11.1-slim-bullseye as get_models
RUN apt-get update -y && apt-get upgrade -y && apt-get install git git-lfs make -y

# Get models
COPY Makefile .
RUN make whisper-models

FROM python:3.11.1-slim-bullseye
COPY --from=get_models models/ /srv/models/
