# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r transcribe-batch/requirements.txt 
        make install-dev-tools
    - name: Test
      run: |
        make test
    - name: check code
      run: |
        make run-check-code
